name: build
on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          bash build.sh

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          name: emscripten-ports
          generate_release_notes: true
          tag_name: ${{ github.ref }}
          files: ports.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
